apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "FhrdvI1h1xx6YRhov6GrhwXS/O6S0FncKPdDkWQp61zmmT0xg/xetxmxeWBNKAe7\n8k4zBVvzi1cB21G+0HaRTTO5qzB4Y0dpa8EH0WKCRnas9yDjv/cyV42M/WLOspdd\nIZgClAIyyFtvv/IxofwlDbENx3xWaR3eqpxI/K1Pkv0="
