apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "D5FZgjMsjvGlGZX7LO4PA+9ZigmugTP2avQRwyVvlkqaLA9kNZT+Q6NOpdVyP2gZ\nsG6/AoT1LHuYhWIRDIqzPdUbeLRduzErQqW/d7NXm6IPsiFuMKP9HTlMNw1yAw7T\nNLLaBNVMsnbMdRqVWEr2KLuYLNfcB/0SwxkkggyJ6GI="
