apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "qB28ZUJd8ASCL+7E4cFKQr3to3RxsqiLMfXuuFWY4F4yP3z3OgzQar4VbDD5a4IN\nJrPtTKSATSai99s4MRRA3Hlx4tbAVUY0vnkDgA39Ih8F8AQG3/lUxf7IgdlHNnFC\nIM/r7gs+uXijzyvqi9Gw6FkqhomsuUyNtq2c65oesEk="
