apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "iF+MD4vQEyDdnO5bosYMr8D0hpPVXQEb6CdTJ53EWGy4HMsXFVwb9WdJIroJ18Ro\n6ZF/3HRdHL/85ABldyfQB/yVtTbap8svtbyxiY2mW2t38Twb6Vzh3Q8MdAnNkCmx\nSCeAfQYMbKm8dvXP956PkBm2qdWO6gEnHYXaGeist6w="
