apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "pUocSQC90KAkXF+3AfykJd2TRaNGfFm774/ArdXfPIBcNcA23lz3Ecl+xqtvDPdt\njptMZqT4Nl6MwXCyWnK9mQ6yZvFSgN/JczQ2frG6Mu6aBsGvWrzLlV4G+oACHr8A\ngqBfsglhSMGtvaImmthSAHQ0wbqflo4v8PzZGdLIQgw="
