apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "bSV9T90UV/FxSOB8WfCMAEJpCFxkhI5vTJF0innnLYYQIAEGeEyq6WFRnI6QFmYi\nF9GsE3pw2n3Thoq1kzRC2DKsRybTfrSIEl3OO6t8lnL3Y8MgQKDkh2Kc6hcs64dW\nXnRIZkqmtrh/qiDpr2iGQz293AeMwL4kYU1HdQtHjTc="
