apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "zN+Zy0X1IRbClzM3nwFJo4TbO4rpftZhTWk6oiBCrmxGsHwy9iUPFKxlsiB5ijnO\nPouyllcDk0UwcVLIxdP9e2fWDjmqrKLredGxWvMmgU3aLISkk2H0TcDT7hpi1xp/\nW4H+jnNS3j9/I9UXLVKujq7Xw0s5wgVMn4S3W8nhFdk="
