apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "3jAR2+IoqiQe6lSI9dZsvmcAT/1z2jLCJya7JYVZmS24Fp6G4K2kepZ4O5vWxL1c\nEaDAzepCv3rPJRYAo/w1LwHuetfp8ivOj4UlC2H6dcw69KoPT2MCzLneavI/Yn4S\nZ/pz58tJxGzwWc24hin0/YnF0J0DyvdwjNwsI9WAvkk="
